// Default
http://127.0.0.1:5000

// Default buffer scope
-fsSL
--connect-timeout 10

// Default headers
Accept: **/**
--

--
# to get the installation script
GET /i

--
# to get all saved aliases
GET /all

--
# to search for aliases from the search item
GET /search?q=update

--
# to get the the saved alias 
# in-30505
GET /43a6

--
Content-Type: application/json
POST /new
{
  "title": "Install vagrant on Debian",
  "content": "sudo apt-get install vagrant\n",
  "description": "This is the description content as a markdown !"
}

