// Default
http://127.0.0.1:5000

// Default buffer scope
-fsSL
--connect-timeout 10

// Default headers
Accept: **/**
--

--
# to get the installation script
GET /i

--
# to get all saved aliases
GET /all

--
# to search for aliases from the search item
GET /search?q=update

--
# to get the the saved alias 
# in-30505
GET /we-9919f

--
Content-Type: application/json
POST /new
{
  "title": "Install QEMU on ubuntu",
  "content": "sudo apt update\nsudo install qemu"
}

